### ISSUE TITLE
fizzbuzz with if, for

### ISSUE THREAD

**Issue by dg60866090** [dg60866090/pibo#1]
## Tasks

- [] For statement (ragne : 1 to 15)
- [] Print 'fizz' if is times of 3 
- [] Print 'fizz' if is times of 5
- [] Print 'fizz' if is times of 15
